import Head from 'next/head';
import dynamic from 'next/dynamic';
import ToolShell from '../../components/Tools/ToolShell';
import ToolSEOContent from '../../components/Tools/ToolSEOContent';
import { generateBreadcrumbs, generateFaqSchema, generateSoftwareAppSchema, SITE_URL } from '../../utils/siteConfig';

const FaviconGenerator = dynamic(() => import('../../components/Image/FaviconGenerator'), {
  ssr: false,
  loading: () => <div className="text-center py-12 text-slate-500 text-sm">Loading…</div>,
});

const SLUG = '/image/favicon-generator';

const FAQS = [
  { q: 'Is my image uploaded to a server?', a: 'No. The entire favicon generation runs in your browser using JavaScript Canvas APIs. Your image never leaves your device, never touches our servers, and is never logged or stored anywhere.' },
  { q: 'What image formats are supported?', a: 'JPG, PNG, WebP, AVIF, GIF, BMP, and HEIC (iPhone photos). The tool auto-detects the format — just drop any image file.' },
  { q: 'What is the maximum file size?', a: 'You can process images up to ~50 MB. Files over 25 MB will be slower, especially on mobile. For very large images, try resizing first with our Image Resizer.' },
  { q: 'Will this work on mobile?', a: 'Yes, on modern iOS Safari and Chrome for Android. Very large images (>25 MB) may be slow on older devices due to memory constraints.' },
  { q: 'What sizes does the favicon pack include?', a: 'The pack generates six files: favicon-16x16.png (16×16), favicon-32x32.png (32×32), apple-touch-icon.png (180×180), android-chrome-192x192.png (192×192), android-chrome-512x512.png (512×512), and favicon.ico (embedding both 16×16 and 32×32 PNGs in a single ICO container). Plus a site.webmanifest for PWA support.' },
  { q: 'What is favicon.ico and do I still need it?', a: 'favicon.ico is the legacy format that browsers look for at the root of your domain (/favicon.ico). While modern HTML can load PNG favicons via a <link> tag, the .ico file provides a fallback for older browsers and is also used by some desktop shortcuts and bookmark icons. This tool builds a proper ICO binary containing both 16×16 and 32×32 PNG versions.' },
  { q: 'What is an Apple Touch Icon?', a: 'Apple devices use a specific icon when a user adds your site to their home screen (Add to Home Screen). The required size is 180×180 pixels for iOS. The apple-touch-icon.png generated by this tool is the correct size and format — just place it in your site root and link it in your HTML head.' },
  { q: 'What is site.webmanifest and do I need it?', a: 'A web manifest is a JSON file that tells browsers how to display your site when installed as a Progressive Web App (PWA). It defines the name, icons, theme color, and display mode. This tool generates a manifest with the Android Chrome icon references — you just need to fill in the "name" field with your site name.' },
];

export default function FaviconGeneratorPage() {
  const breadcrumbSchema = generateBreadcrumbs(SLUG);
  const softwareSchema = generateSoftwareAppSchema({
    name: 'Favicon Generator',
    slug: SLUG,
    description: 'Generate a complete favicon pack from any image — ICO, Apple Touch, Android Chrome, and PWA manifest icons. 100% client-side, no upload.',
    category: 'UtilitiesApplication',
    featureList: 'ICO binary generation (16+32px), Apple touch icon 180px, Android Chrome 192+512px, PWA manifest, All PNG output, ZIP download, No upload, No sign-up, Privacy-first',
  });
  const faqSchema = generateFaqSchema(FAQS);

  return (
    <>
      <Head>
        <title>Favicon Generator — Complete Favicon Pack, No Upload | Toolisk</title>
        <meta name="description" content="Generate a complete favicon pack from any image — ICO, Apple Touch, and PWA manifest icons. 100% client-side, no upload, private, free." />
        <meta name="keywords" content="favicon generator, generate favicon, favicon pack, favicon.ico, apple touch icon, android chrome icon, pwa manifest, favicon no upload, favicon online private, favicon from image free, web app icon generator" />
        <link rel="canonical" href={`${SITE_URL}${SLUG}`} />
        <meta property="og:title" content="Favicon Generator — Complete Favicon Pack, No Upload | Toolisk" />
        <meta property="og:description" content="Generate a complete favicon pack from any image — ICO, Apple Touch, and PWA icons. No upload, 100% private." />
        <meta property="og:url" content={`${SITE_URL}${SLUG}`} />
        <meta property="og:type" content="website" />
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify([breadcrumbSchema, softwareSchema, faqSchema]) }}
        />
      </Head>

      <ToolShell
        icon="&#127760;"
        title="Favicon Generator"
        tagline="Generate a complete favicon pack from any image — ICO, Apple Touch, Android Chrome, and PWA manifest icons. 100% client-side, no upload."
        gradient="from-sky-600 via-blue-600 to-cyan-500"
        parent="image"
      >
        <FaviconGenerator />
      </ToolShell>

      <ToolSEOContent
        description="Generate a complete favicon pack — favicon.ico, 16×16 and 32×32 PNGs, Apple Touch Icon (180×180), Android Chrome icons (192×192 and 512×512), and a PWA site.webmanifest — all from a single image. Runs entirely in your browser: no upload, no sign-up, no watermark."
        features={[
          '&#128274; 100% client-side — your image never leaves your browser',
          '&#127760; Generates proper ICO binary with 16×16 and 32×32 PNGs embedded',
          '&#127822; Apple Touch Icon at 180×180 for iOS home screen',
          '&#128241; Android Chrome icons at 192×192 and 512×512',
          '&#128196; Includes site.webmanifest for PWA support',
          '&#128230; Download all files individually or as a single .zip',
        ]}
        steps={[
          { title: 'Upload your image', desc: 'Drop a square or high-resolution image — ideally a logo or icon with transparent background. Your image stays local.' },
          { title: 'Review the output set', desc: 'See all seven files that will be generated: five PNGs at different sizes, a favicon.ico, and a site.webmanifest.' },
          { title: 'Generate the favicon pack', desc: 'Click "Generate Favicon Pack" and each size is rendered client-side using the Canvas API — no upload, no server.' },
          { title: 'Download and deploy', desc: 'Download individual files or grab everything as a .zip. Place the files in your website root and add the link tags to your HTML.' },
        ]}
        faqs={FAQS}
        body={
          <section className="space-y-4">
            <h2 className="text-2xl font-bold text-slate-900">What is a favicon and why does every website need one?</h2>
            <p className="text-slate-600 leading-relaxed">
              A favicon (short for "favorite icon") is the small icon that appears in browser tabs, bookmarks, search results, and mobile home screens. It is one of the most visible branding elements of any website — a 16×16 or 32×32 pixel square that users see dozens of times a day as they navigate between tabs. Without a favicon, your site shows a generic globe or blank document icon, which looks unprofessional and makes your tab harder to find. With a properly generated favicon pack, your brand appears consistently across every platform: desktop browsers (Chrome, Firefox, Safari, Edge), iOS home screens, Android Chrome, and even desktop shortcuts.
            </p>
            <p className="text-slate-600 leading-relaxed">
              Modern browsers also expect a set of specific sizes beyond the traditional 16×16 favicon. Apple requires a 180×180 Apple Touch Icon for iOS home screen bookmarks. Android Chrome uses 192×192 and 512×512 icons for the PWA install banner. A proper site.webmanifest file ties these icons together and tells the browser that your site can be installed as a Progressive Web App. This tool generates the entire set — seven files total — from a single source image, using only your browser&apos;s Canvas API. No upload to a remote server, no watermark, and no sign-up: the entire pipeline runs on your device.
            </p>

            <h3 className="text-xl font-bold text-slate-900 mt-8">The seven files in a complete favicon pack</h3>
            <p className="text-slate-600 leading-relaxed">
              A production-ready favicon deployment needs more than a single favicon.ico. Here is every file this tool generates and its specific purpose:
            </p>
            <div className="overflow-x-auto mt-3">
              <table className="w-full text-sm text-left border-collapse">
                <thead>
                  <tr className="border-b border-slate-200">
                    <th className="py-2 pr-4 font-semibold text-slate-700">File</th>
                    <th className="py-2 pr-4 font-semibold text-slate-700">Size</th>
                    <th className="py-2 font-semibold text-slate-700">Purpose</th>
                  </tr>
                </thead>
                <tbody>
                  <tr className="border-b border-slate-100">
                    <td className="py-2 pr-4 text-slate-800 font-mono text-xs">favicon-16x16.png</td>
                    <td className="py-2 pr-4 text-slate-500">16&times;16</td>
                    <td className="py-2 text-slate-600">Standard browser tab favicon</td>
                  </tr>
                  <tr className="border-b border-slate-100">
                    <td className="py-2 pr-4 text-slate-800 font-mono text-xs">favicon-32x32.png</td>
                    <td className="py-2 pr-4 text-slate-500">32&times;32</td>
                    <td className="py-2 text-slate-600">HiDPI browser tab favicon</td>
                  </tr>
                  <tr className="border-b border-slate-100">
                    <td className="py-2 pr-4 text-slate-800 font-mono text-xs">apple-touch-icon.png</td>
                    <td className="py-2 pr-4 text-slate-500">180&times;180</td>
                    <td className="py-2 text-slate-600">iOS home screen icon (Add to Home Screen)</td>
                  </tr>
                  <tr className="border-b border-slate-100">
                    <td className="py-2 pr-4 text-slate-800 font-mono text-xs">android-chrome-192x192.png</td>
                    <td className="py-2 pr-4 text-slate-500">192&times;192</td>
                    <td className="py-2 text-slate-600">Android Chrome PWA icon (small)</td>
                  </tr>
                  <tr className="border-b border-slate-100">
                    <td className="py-2 pr-4 text-slate-800 font-mono text-xs">android-chrome-512x512.png</td>
                    <td className="py-2 pr-4 text-slate-500">512&times;512</td>
                    <td className="py-2 text-slate-600">Android PWA install banner &amp; splash screen</td>
                  </tr>
                  <tr className="border-b border-slate-100">
                    <td className="py-2 pr-4 text-slate-800 font-mono text-xs">favicon.ico</td>
                    <td className="py-2 pr-4 text-slate-500">16+32</td>
                    <td className="py-2 text-slate-600">Legacy ICO container for bookmark icons and older browsers</td>
                  </tr>
                  <tr>
                    <td className="py-2 pr-4 text-slate-800 font-mono text-xs">site.webmanifest</td>
                    <td className="py-2 pr-4 text-slate-500">—</td>
                    <td className="py-2 text-slate-600">PWA manifest defining app name, icons, and display mode</td>
                  </tr>
                </tbody>
              </table>
            </div>

            <h3 className="text-xl font-bold text-slate-900 mt-8">How to deploy your favicon pack</h3>
            <p className="text-slate-600 leading-relaxed">
              Place all the generated PNG and ICO files in the root of your website (typically the <code className="bg-slate-100 px-1.5 py-0.5 rounded text-sm">public/</code> folder for Next.js or the root of your <code className="bg-slate-100 px-1.5 py-0.5 rounded text-sm">static/</code> directory). Then add the following link tags inside your <code className="bg-slate-100 px-1.5 py-0.5 rounded text-sm">&#60;head&#62;</code>:
            </p>
            <div className="bg-slate-900 text-slate-200 rounded-lg p-4 text-xs font-mono leading-relaxed overflow-x-auto mt-3">
              {`<link rel="icon" type="image/png" href="/favicon-16x16.png" sizes="16x16" />
<link rel="icon" type="image/png" href="/favicon-32x32.png" sizes="32x32" />
<link rel="apple-touch-icon" href="/apple-touch-icon.png" />
<link rel="icon" type="image/png" href="/android-chrome-192x192.png" sizes="192x192" />
<link rel="icon" type="image/png" href="/android-chrome-512x512.png" sizes="512x512" />
<link rel="manifest" href="/site.webmanifest" />`}
            </div>
            <p className="text-slate-600 leading-relaxed">
              The <code className="bg-slate-100 px-1.5 py-0.5 rounded text-sm">favicon.ico</code> should also be in the root directory as a fallback. Edit the <code className="bg-slate-100 px-1.5 py-0.5 rounded text-sm">site.webmanifest</code> to replace the empty <code className="bg-slate-100 px-1.5 py-0.5 rounded text-sm">"name"</code> field with your actual site name. Once deployed, run a hard refresh and check all your browsers, mobile devices, and PWA install prompts — your brand should now appear consistently everywhere.
            </p>

            <h3 className="text-xl font-bold text-slate-900 mt-8">Why no-upload matters for favicon generation</h3>
            <p className="text-slate-600 leading-relaxed">
              Most online favicon generators work by having you upload your logo or image to their server, where it is resized, converted, and packaged into the various icon formats. That may seem harmless, but you are handing over the highest-resolution version of your brand assets — often including the vector source — to a third party. They may cache it, watermark it, include it in their gallery, or use it without your consent. For businesses, this is an intellectual property risk. For personal projects, it is simply unnecessary.
            </p>
            <p className="text-slate-600 leading-relaxed">
              This tool processes everything inside your browser&apos;s JavaScript runtime. The Canvas API renders each size, the PNG blobs are assembled directly in memory, and the ICO binary is constructed byte-by-byte using a DataView — no network call is ever made with your image data. The only bytes that leave your machine are the finished icon files streaming to your downloads folder. You get a complete, production-grade favicon pack without exposing your source art to anyone.
            </p>

            <h3 className="text-xl font-bold text-slate-900 mt-8">Common mistakes when setting up favicons</h3>
            <ul className="list-disc pl-5 space-y-2 text-slate-600">
              <li><strong>Using a single favicon.ico:</strong> Modern browsers look for specific PNG sizes. Serving only an ICO file means missed HiDPI rendering and broken home screen icons.</li>
              <li><strong>Missing the Apple Touch Icon:</strong> Without a 180×180 apple-touch-icon.png, iOS devices show a low-quality thumbnail when users add your site to their home screen.</li>
              <li><strong>Wrong canvas ratio:</strong> Favicon and app icons must be square. If you drop a rectangular source image, the tool will stretch it — use a square logo or crop to a square first.</li>
              <li><strong>Using a complex photograph:</strong> Favicons are tiny — 16&times;16 pixels is barely two characters wide. Simple, bold shapes and letters work best; detailed photos become illegible at small sizes.</li>
              <li><strong>Forgetting the webmanifest:</strong> Without site.webmanifest, Android Chrome cannot present your site as an installable PWA, and you lose the install banner and splash screen features.</li>
            </ul>
          </section>
        }
        relatedTools={[
          { name: 'Image Resizer', href: '/image/resize-image', icon: '&#128208;' },
          { name: 'Convert to PNG', href: '/image/convert-to-png', icon: '&#127912;' },
          { name: 'Image Compressor', href: '/image/compress-image', icon: '&#128392;' },
        ]}
      />
    </>
  );
}
